version: "3.8"

services:
  repository-fetcher:
    build:
      context: .
      dockerfile: Dockerfile.cron
    container_name: contribute-cron
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
    restart: unless-stopped
    volumes:
      - cron_logs:/var/log/cron

volumes: cron_logs
